spring:
  output:
    ansi:
      enabled: detect

#logging para spring boot
logging:
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 25MB
  file:
    name: application.log
#  pattern:
#    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: INFO
    '[org.apache.coyote.http11.Http11InputBuffer]': INFO
    '[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]': INFO
    '[org.springframework.security]': DEBUG
    '[es.seresco]': DEBUG


appz:
  security:

    authentication:
      in-memory:
        # password
        password: $2a$10$U4RvjPPecYcXj8ofw8WnXeLNwOvRkKkt1mv59X3oZzsh94qNmKq9O
        # 01234
#        password: $2a$10$lb0QZlRNjPVvpxJ741ghb.p23Wlde19MMLNBOaI/jaeSpAtn7U2Jy

    http:
      form:
        enabled: true
        # Specifies the URL to send users to if login is required
        login-page: /login
        # Specifies the URL to validate the credentials using POST method.
        login-processing-url: /login
        # Specifies where users will be redirected after authenticating successfully if they have not visited a secured page prior to authenticating
        authentication-success-url: /login?success
        # the URL to send users if authentication fails (i.e. "/login?error").
        authentication-failure-url: /login?error
        # how is the name of fields used to configure the login form
        username-parameter: username
        password-parameter: password
        # Forward Authentication Success Handler url
        success-forward-url: 
        # Forward Authentication Failure Handler url
        failure-forward-url: 
      logout:
        enabled: true
        # The URL that triggers log out to occur
        processing-url: /logout
        # The URL to redirect to after logout has occurred.
        success-url: /login?logout
      basic:
        enabled: true
        realm: VIDEOCLUPY!
      exception-handling:
        enabled: true
        # the URL to the access denied page (i.e. /errors/401)
        access-denied-page: /login?denied

