spring:
  output:
    ansi:
      enabled: detect

#logging para spring boot
logging:
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 25MB
  file:
    name: application.log
#  pattern:
#    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: INFO
    '[org.apache.coyote.http11.Http11InputBuffer]': INFO
    '[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]': INFO
    '[es.seresco]': DEBUG
